services:
  - type: web
    name: student-registration-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && node index.js
    envVars:
      - key: MONGO_URI
        value: YOUR_MONGODB_ATLAS_URI_HERE
    autoDeploy: true
